# Generated by Django 5.0.4 on 2024-06-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_payment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='phone',
        ),
    ]
