# Generated by Django 5.0.4 on 2024-06-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_hotelcheckout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelcheckout',
            old_name='people',
            new_name='tour_travellers',
        ),
        migrations.RemoveField(
            model_name='hotelcheckout',
            name='hotel_booking',
        ),
        migrations.AddField(
            model_name='hotelcheckout',
            name='tour_date',
            field=models.DateField(null=True),
        ),
    ]
