# Generated by Django 5.0.4 on 2024-06-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_payment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcheckout',
            name='tour_date',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
